version: "3.9"
services:

  #PHP Service
  erp_app:
    image: php:8.1-fpm-alpine
    container_name: erp_app
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      tags:
        - "bof-app"
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - mysql_db
      - webserver
    networks:
      - app_network

  #Nginx Service
  webserver:
    image: nginx:1.25.1-alpine-slim
    container_name: webserver
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app_network

  #MySQL Service
  mysql_db:
    container_name: mysql_db
    image: mysql:8.0.33
    restart: unless-stopped
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    tty: true
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: bof_erp
      MYSQL_ROOT_PASSWORD: bof_erp_password
      MYSQL_USER: bof_erp_user
      MYSQL_PASSWORD: bof_erp_password
    networks:
      - app_network

#Docker Networks
networks:
  app_network:
    driver: bridge
volumes:
  dbdata:
    driver: local