name: BOF ERP deployement

on:
  push:
    branches:
      - stage

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Copy file via scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.BOF_STG_HOST }}
          username: ${{ secrets.BOF_STG_USER }}
          port: ${{ secrets.BOF_STG_PORT }}
          password: ${{ secrets.BOF_STG_PASS }}
          source: "."
          target: "/var/www/bof"

      - name: executing laravel deployement commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.BOF_STG_HOST }}
          username: ${{ secrets.BOF_STG_USER }}
          port: ${{ secrets.BOF_STG_PORT }}
          password: ${{ secrets.BOF_STG_PASS }}
          script: |
            cd /var/www/bof
            echo "creating env file...."
            php -r "file_exists('.env') || copy('.env.example', '.env');"
            echo "executing composer install...."
            composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
            echo "Granting directory permissions..."
            chmod -R 777 bootstrap/
            chmod -R 777 storage/
            chmod -R 777 public/
            echo "running migration"
            php artisan migrate
            echo "Cache clear..."
            php artisan cache:clear
            echo "Optimize clear..."
            php artisan optimize:clear
             php artisan optimize
            echo "done...."
